### ISSUE TITLE
Get list of packages from repos

### ISSUE THREAD

**Issue by tcartwright** [ethanbergstrom/Cobalt#14]
How do you get a list of available packages to install?

**Comment by ethanbergstrom** [comment]
Assuming you mean 'all' packages - there's not currently a way to do that. The 'Find' cmdlet very intentionally only searches by ID because it's the least ambiguous identifier for a Winget package, so you will need to search by ID.

I would direct you to https://learn.microsoft.com/en-us/windows/package-manager/winget/search#show-all on how to get a list of all package names from the native WinGet CLI, or otherwise wait for the official PowerShell module from the WinGet team at Microsoft.
