### ISSUE TITLE
name property and version type

### ISSUE THREAD

**Issue by jszabo98** [ethanbergstrom/Cobalt#19]
I miss the name column in "winget list" that get-wingetpackage doesn't show.  It would be nice if the version property were type [version].  I understand parsing winget is a challenge.

**Comment by ethanbergstrom** [comment]
Regarding package name, see #15.

Regarding casting the version as a Version, the issue is winget itself does not have any sort of formal version definition, which means if I were to cast everything as a Version, it could cause some packages to not emit properly or generate an error. See also: https://github.com/microsoft/winget-cli/discussions/284#discussioncomment-99519
