### ISSUE TITLE
Get-WinGetPackage throwing MethodInvocationException when package name contains Japanese characters

### ISSUE THREAD

**Issue by dxman** [ethanbergstrom/Cobalt#23]
This issue appears to be fairly similar to #12 which deals with an exception being thrown by `Get-WinGetPackage` when German-localized package names are present. I have a number of games installed which contain Japanese characters in the their titles, and that appears to be the cause of the exception this time around. The exact error text is as follows:

```
MethodInvocationException: Exception calling "Substring" with "2" argument(s): "Index and length must refer to a location within the string.
(Parameter 'length')"
InvalidOperation: You cannot call a method on a null-valued expression.
```

Thanks for all your hard work!

**Comment by ethanbergstrom** [comment]
#12 was a bit different, in that it was failing on German-localized headers of the columnar output. 

If the issue is with the package names itself, unfortunately I don't think I'll be able to fix this one, as I filter out 'junk' characters (that WinGet CLI creates when it truncates columnar output) with the [IsBasicLatin regex character set](https://github.com/ethanbergstrom/Cobalt/blob/v0.4.0/src/Cobalt.ps1#L73), which is probably filtering out your package names, too. If you can provide a couple examples of output straight from WinGet, I can give it a try, but no promises :) 

I would recommend looking into Microsoft's native WinGet PowerShell module to see if it might serve your particular use case better.
